#!/usr/bin/env bash
# This script pings an IP address passed as an argument.

# Check if an argument is passed
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the provided IP address 5 times
ping -c 5 "$1"